# E-Gov Guardian Security Scanner Configuration Template
#
# SECURITY NOTICE:
# This is a template file. Copy this to 'config.yaml' and fill in your actual values.
# NEVER commit config.yaml with real API keys to version control!

# OWASP ZAP Configuration (Optional - enhanced scanning)
zap:
  enabled: false # Set to true if you have ZAP installed locally or via Docker
  host: "127.0.0.1"
  port: 8080
  api_key: null # Optional ZAP API key for authenticated access
  docker:
    enabled: false # Set to true to use ZAP via Docker
    image: "owasp/zap2docker-stable"

# Alternative Built-in Scanner (Always enabled)
alternative_scanners:
  enabled: true
  use_builtin_checks: true

# AI Analysis Configuration
ai_analysis:
  enabled: false # Will be toggled by user in web interface
  openai_api_key: "YOUR_OPENAI_API_KEY_HERE" # Replace with your actual OpenAI API key
  model: "gpt-4o-mini" # Using GPT-4o-mini for better quality recommendations
  max_tokens: 150 # Keep recommendations short (1-2 lines)
  temperature: 0.1 # Low temperature for consistent technical advice

# Scanner Configuration
scanner:
  max_scan_time: 1800 # 30 minutes
  max_depth: 5
  thread_count: 10
  deep_scan_depth: 8

# Vulnerability Detection Settings
vulnerabilities:
  sql_injection:
    enabled: true
    severity_threshold: "Medium"
  xss:
    enabled: true
    severity_threshold: "Medium"
  insecure_headers:
    enabled: true
  insecure_cookies:
    enabled: true
  port_scan:
    enabled: true
    common_ports: [80, 443, 22, 21, 25, 53, 110, 993, 995, 8080, 8443]
  malware_check:
    enabled: true

# Reporting Configuration
reporting:
  output_format: "json" # json, html, csv, pdf
  detailed_report: true
  include_ai_recommendations: true # Include AI recommendations when available

# Debug and Logging
debug: false
log_file: null # Set to file path for file logging, null for console only
